services:
  api-organ-eyes:
    build: .
    command: npm run dev
    ports:
      - 4000:4000
    links:
      - db
    volumes:
      - ./app:/usr/src/app
      - ./node_modules:/usr/src/node_modules
      
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306

